# 物件導向程式設計HW

# 用sklearn測試

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
scaler.mean_

array([-0.125,  9.   ])

In [12]:
scaler.var_

array([ 0.546875, 35.      ])

In [13]:
scaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [15]:
scaler.transform([[1,2]])

array([[ 1.52127766, -1.18321596]])

# 自己的StandradScaler

In [16]:
import numpy as np

In [97]:
np.mean(data, axis=0)

array([-0.125,  9.   ])

In [98]:
np.var(data, axis=0)

array([ 0.546875, 35.      ])

In [99]:
(np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [100]:
class MyStandardScaler: 
    
    def __init__(self):                            
        self.mean = None
        self.var = None
        
    def fit(self,data):                           
        self.mean = np.mean(data, axis=0)
        self.var  = np.var(data, axis=0)
        
    def transform(self,data):
        return (np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

# 測試結果是否一致

In [101]:
myscaler = MyStandardScaler()

In [102]:
myscaler.fit(data)

In [103]:
myscaler.mean

array([-0.125,  9.   ])

In [104]:
myscaler.var

array([ 0.546875, 35.      ])

In [105]:
myscaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [107]:
myscaler.transform([[1,2]])

array([[ 1.52127766, -1.18321596]])

# 結果一致欸~